                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ThesslaGreenCoordinator' object has no attribute 'last_update_success_time'. Did you mean: 'last_update_success'?[0m
[33m2025-08-06 10:37:57.300 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[31m2025-08-06 10:37:57.750 ERROR (MainThread) [custom_components.hacs] Download failed - Got status code 404 when trying to download https://github.com/blakinio/thesslagreen/archive/refs/heads/20fe962.zip
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 709, in async_download_file
    raise HacsException(
    ...<2 lines>...
    )
custom_components.hacs.exceptions.HacsException: Got status code 404 when trying to download https://github.com/blakinio/thesslagreen/archive/refs/heads/20fe962.zip[0m
[31m2025-08-06 10:37:57.751 ERROR (MainThread) [custom_components.hacs] [<Integration blakinio/thesslagreen>] Failed to download zipball
Traceback (most recent call last):
  File "/config/custom_components/hacs/repositories/base.py", line 631, in download_content
    await self.download_repository_zip()
  File "/config/custom_components/hacs/repositories/base.py", line 677, in download_repository_zip
    raise HacsException(f"[{self}] Failed to download zipball")
custom_components.hacs.exceptions.HacsException: [<Integration blakinio/thesslagreen>] Failed to download zipball[0m
[33m2025-08-06 10:37:58.136 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 10:38:01.306 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration xtend_tuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:01.308 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration philips_ambilight_hue which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:01.310 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration waste_management which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:01.311 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration thessla_green_modbus which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:01.312 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration satel which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:01.313 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:01.314 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration irrigationprogram which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:01.315 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:01.315 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration edgeos which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:01.316 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:01.316 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration dahua which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:01.317 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:01.317 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hikconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:01.318 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
s6-rc: info: service legacy-services: stopping
[33m2025-08-06 10:38:10.082 WARNING (MainThread) [homeassistant.core] Task <Task pending name='admin service homeassistant.restart' coro=<async_setup.<locals>.async_handle_core_service() running at /usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py:233> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[set.remove(), Task.task_wakeup()]> was still running after final writes shutdown stage; Integrations should cancel non-critical tasks when receiving the stop event to prevent delaying shutdown[0m
Found 3 non-daemonic threads.
[08:38:25] INFO: [32mHome Assistant Core finish process exit code 0[0m
[08:38:25] INFO: [32mHome Assistant Core service shutdown[0m
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun home-assistant (no readiness notification)
s6-rc: info: service legacy-services successfully started
[33m2025-08-06 10:38:57.154 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xtend_tuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:57.156 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration philips_ambilight_hue which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:57.157 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration waste_management which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:57.158 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration thessla_green_modbus which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:57.160 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration satel which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:57.161 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:57.162 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration irrigationprogram which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:57.163 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:57.164 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration edgeos which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:57.165 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:57.166 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dahua which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:57.167 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:57.168 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hikconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:38:57.169 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 10:39:11.625 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/aiomusiccast/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
[0m
[33m2025-08-06 10:39:12.581 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.13/site-packages/gql/transport/aiohttp.py:92: UserWarning: WARNING: By default, AIOHTTPTransport does not verify ssl certificates. This will be fixed in the next major version. You can set ssl=True to force the ssl certificate verification or ssl=False to disable this warning
  warnings.warn(
[0m
[32m2025-08-06 10:39:14.328 INFO (MainThread) [custom_components.thessla_green_modbus] Setting up ThesslaGreen Modbus integration (Enhanced v2.0)[0m
[36m2025-08-06 10:39:14.329 DEBUG (MainThread) [custom_components.thessla_green_modbus] Configuration: host=192.168.3.17, port=8899, slave_id=10, scan_interval=30, timeout=10, retry=3[0m
[32m2025-08-06 10:39:14.329 INFO (MainThread) [custom_components.thessla_green_modbus] Scanning device capabilities...[0m
[36m2025-08-06 10:39:14.329 DEBUG (MainThread) [custom_components.thessla_green_modbus.device_scanner] Initialized device scanner for 192.168.3.17:8899 (slave_id=10)[0m
[32m2025-08-06 10:39:14.331 INFO (MainThread) [custom_components.thessla_green_modbus.device_scanner] Connected to 192.168.3.17:8899, starting enhanced capability scan...[0m
[36m2025-08-06 10:39:14.343 DEBUG (SyncWorker_2) [pymodbus.logging] Connection to Modbus server established. Socket ('192.168.1.83', 55252)[0m
[36m2025-08-06 10:39:14.344 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Connected to Modbus device, scanning registers...[0m
[33m2025-08-06 10:39:14.991 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.29.5 is exactly one major version older than the runtime version 6.31.1 at api.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
[0m
[33m2025-08-06 10:39:15.009 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.29.5 is exactly one major version older than the runtime version 6.31.1 at api_options.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
[0m
[31m2025-08-06 10:39:17.860 ERROR (MainThread) [homeassistant.components.sensor] hikconnect: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 788, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1303, in async_device_update
    await self.async_update()
  File "/config/custom_components/hikconnect/sensor.py", line 64, in async_update
    res = await asyncio.wait_for(get_call_status_coro, SCAN_INTERVAL_TIMEOUT.seconds)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hikconnect/api.py", line 233, in get_call_status
    raise DeviceOffline()
hikconnect.exceptions.DeviceOffline[0m
[31m2025-08-06 10:39:18.292 ERROR (MainThread) [homeassistant.components.sensor] hikconnect: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 788, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1303, in async_device_update
    await self.async_update()
  File "/config/custom_components/hikconnect/sensor.py", line 64, in async_update
    res = await asyncio.wait_for(get_call_status_coro, SCAN_INTERVAL_TIMEOUT.seconds)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hikconnect/api.py", line 233, in get_call_status
    raise DeviceOffline()
hikconnect.exceptions.DeviceOffline[0m
[36m2025-08-06 10:39:24.429 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x1 0x0 0x0 0x0 0x11 0xa 0x4 0xe 0x0 0xb6 0x0 0xc1 0x0 0xfb 0x0 0xbb 0x80 0x0 0x80 0x0 0x1 0xa[0m
[36m2025-08-06 10:39:24.430 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(4 sub -1) -> ReadInputRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[182, 193, 251, 187, 32768, 32768, 266], status=1) [0m
[36m2025-08-06 10:39:24.430 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 10:39:24.430 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Input register batch 16-22: 7 registers found[0m
[36m2025-08-06 10:39:24.581 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x2 0x0 0x0 0x0 0x3 0xa 0x84 0x2[0m
[36m2025-08-06 10:39:24.581 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 10:39:24.581 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Input register batch 32-35 failed: ExceptionResponse(dev_id=10, function_code=132, exception_code=2)[0m
[36m2025-08-06 10:39:24.763 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x3 0x0 0x0 0x0 0x3 0xa 0x84 0x2[0m
[36m2025-08-06 10:39:24.763 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 10:39:24.763 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Input register batch 48-51 failed: ExceptionResponse(dev_id=10, function_code=132, exception_code=2)[0m
[36m2025-08-06 10:39:24.942 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x4 0x0 0x0 0x0 0x3 0xa 0x84 0x2[0m
[36m2025-08-06 10:39:24.943 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 10:39:24.943 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Input register batch 64-68 failed: ExceptionResponse(dev_id=10, function_code=132, exception_code=2)[0m
[36m2025-08-06 10:39:25.126 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x5 0x0 0x0 0x0 0x3 0xa 0x84 0x2[0m
[36m2025-08-06 10:39:25.126 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 10:39:25.126 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Input register batch 80-83 failed: ExceptionResponse(dev_id=10, function_code=132, exception_code=2)[0m
[36m2025-08-06 10:39:25.325 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x6 0x0 0x0 0x0 0x3 0xa 0x84 0x2[0m
[36m2025-08-06 10:39:25.325 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 10:39:25.325 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Input register batch 96-99 failed: ExceptionResponse(dev_id=10, function_code=132, exception_code=2)[0m
[36m2025-08-06 10:39:25.516 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x7 0x0 0x0 0x0 0x3 0xa 0x84 0x2[0m
[36m2025-08-06 10:39:25.516 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 10:39:25.516 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Input register batch 112-114 failed: ExceptionResponse(dev_id=10, function_code=132, exception_code=2)[0m
[36m2025-08-06 10:39:25.688 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x8 0x0 0x0 0x0 0x3 0xa 0x84 0x2[0m
[36m2025-08-06 10:39:25.689 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 10:39:25.689 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Input register batch 128-130 failed: ExceptionResponse(dev_id=10, function_code=132, exception_code=2)[0m
[32m2025-08-06 10:39:25.689 INFO (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Input registers scan: 7 registers found[0m
[36m2025-08-06 10:39:25.897 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x9 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x0 0x0 0x0 0x0 0x1 0x0 0x0[0m
[36m2025-08-06 10:39:25.897 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 1, 0], status=1) [0m
[36m2025-08-06 10:39:25.897 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 10:39:25.897 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Holding register batch 4096-4099: 4 registers found[0m
[36m2025-08-06 10:39:26.066 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0xa 0x0 0x0 0x0 0x9 0xa 0x3 0x6 0xd 0xcd 0xe 0xd 0x8 0x0[0m
[36m2025-08-06 10:39:26.066 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[3533, 3597, 2048], status=1) [0m
[36m2025-08-06 10:39:26.066 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 10:39:26.066 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Holding register batch 4112-4114: 3 registers found[0m
[36m2025-08-06 10:39:26.261 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0xb 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 10:39:26.261 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 0, 0], status=1) [0m
[36m2025-08-06 10:39:26.261 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 10:39:26.261 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Holding register batch 4128-4131: 4 registers found[0m
[36m2025-08-06 10:39:26.443 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0xc 0x0 0x0 0x0 0xd 0xa 0x3 0xa 0x0 0x8 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 10:39:26.443 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[8, 0, 0, 0, 0], status=1) [0m
[36m2025-08-06 10:39:26.443 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 10:39:26.443 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Holding register batch 4144-4148: 5 registers found[0m
[36m2025-08-06 10:39:26.612 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0xd 0x0 0x0 0x0 0x9 0xa 0x3 0x6 0x0 0x5 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 10:39:26.613 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[5, 0, 0], status=1) [0m
[36m2025-08-06 10:39:26.613 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 10:39:26.613 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Holding register batch 4160-4162: 3 registers found[0m
[36m2025-08-06 10:39:26.824 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0xe 0x0 0x0 0x0 0xd 0xa 0x3 0xa 0x0 0x8 0x0 0x2 0x0 0x5 0x0 0x5 0x0 0x64[0m
[36m2025-08-06 10:39:26.824 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[8, 2, 5, 5, 100], status=1) [0m
[36m2025-08-06 10:39:26.824 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 10:39:26.824 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Holding register batch 4176-4180: 5 registers found[0m
[36m2025-08-06 10:39:27.009 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0xf 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 10:39:27.009 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 0, 0], status=1) [0m
[36m2025-08-06 10:39:27.009 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 10:39:27.009 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Holding register batch 4192-4195: 4 registers found[0m
[36m2025-08-06 10:39:27.185 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x10 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x1 0x0 0x0 0x0 0x1e 0x0 0x50[0m
[36m2025-08-06 10:39:27.186 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[1, 0, 30, 80], status=1) [0m
[36m2025-08-06 10:39:27.186 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 10:39:27.186 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Holding register batch 4208-4211: 4 registers found[0m
[32m2025-08-06 10:39:27.186 INFO (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Holding registers scan: 32 registers found[0m
[36m2025-08-06 10:39:27.380 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x11 0x0 0x0 0x0 0x3 0xa 0x81 0x2[0m
[36m2025-08-06 10:39:27.380 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 10:39:27.547 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x12 0x0 0x0 0x0 0x3 0xa 0x81 0x2[0m
[36m2025-08-06 10:39:27.547 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 10:39:27.720 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x13 0x0 0x0 0x0 0x3 0xa 0x81 0x2[0m
[36m2025-08-06 10:39:27.720 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[32m2025-08-06 10:39:27.720 INFO (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Coil registers scan: 0 registers found[0m
[36m2025-08-06 10:39:27.901 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x14 0x0 0x0 0x0 0x3 0xa 0x82 0x2[0m
[36m2025-08-06 10:39:27.901 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 10:39:28.084 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x15 0x0 0x0 0x0 0x3 0xa 0x82 0x2[0m
[36m2025-08-06 10:39:28.084 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 10:39:28.283 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x16 0x0 0x0 0x0 0x3 0xa 0x82 0x2[0m
[36m2025-08-06 10:39:28.283 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 10:39:28.474 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x17 0x0 0x0 0x0 0x3 0xa 0x82 0x2[0m
[36m2025-08-06 10:39:28.474 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[32m2025-08-06 10:39:28.474 INFO (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Discrete inputs scan: 0 registers found[0m
[36m2025-08-06 10:39:28.474 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Device info extracted: {'device_name': 'ThesslaGreen AirPack (192.168.3.17)', 'manufacturer': 'ThesslaGreen', 'model': 'AirPack Home', 'firmware': 'Unknown', 'serial_number': None}[0m
[32m2025-08-06 10:39:28.475 INFO (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Capability analysis: 9 capabilities detected[0m
[36m2025-08-06 10:39:28.475 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Detected capabilities: ['basic_control', 'intensity_control', 'temperature_control', 'special_functions', 'gwc_support', 'bypass_support', 'constant_flow', 'comfort_mode', 'advanced_configuration'][0m
[32m2025-08-06 10:39:28.476 INFO (MainThread) [custom_components.thessla_green_modbus.device_scanner] Enhanced scan completed: 39 registers found (39.1% success rate), 9 capabilities detected[0m
[32m2025-08-06 10:39:28.476 INFO (MainThread) [custom_components.thessla_green_modbus] Device scan completed: 7 input registers, 32 holding registers, 9 capabilities[0m
[36m2025-08-06 10:39:28.477 DEBUG (MainThread) [custom_components.thessla_green_modbus.coordinator] Initializing optimized register groups for batch reading...[0m
[36m2025-08-06 10:39:28.477 DEBUG (MainThread) [custom_components.thessla_green_modbus.coordinator] Optimized input_registers: 7 registers grouped into 1 batches[0m
[36m2025-08-06 10:39:28.477 DEBUG (MainThread) [custom_components.thessla_green_modbus.coordinator] Optimized holding_registers: 32 registers grouped into 8 batches[0m
[32m2025-08-06 10:39:28.477 INFO (MainThread) [custom_components.thessla_green_modbus.coordinator] Enhanced coordinator initialized: 192.168.3.17:8899 (slave_id=10, interval=30s, timeout=10s)[0m
[31m2025-08-06 10:39:28.477 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry ThesslaGreen AirPack (192.168.3.17) (192.168.3.17) for thessla_green_modbus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/thessla_green_modbus/__init__.py", line 164, in async_setup_entry
    coordinator.device_scan_result = device_scan_result
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: property 'device_scan_result' of 'ThesslaGreenCoordinator' object has no setter[0m
[31m2025-08-06 10:39:28.679 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({% set t = ( states('sensor.supply_temperature')|float - states('sensor.outside_temperature')|float ) %} {% set u = ( states('sensor.exhaust_temperature')|float - states('sensor.outside_temperature')|float ) %} {{ ( t / u *100 )|round(1) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2446, in forgiving_float_filter
    return float(value)
ValueError: could not convert string to float: 'unknown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 641, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2977, in _render_with_context
    return template.render(**kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2449, in forgiving_float_filter
    raise_no_default("float", value)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1975, in raise_no_default
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Template error: float got invalid input 'unknown' when rendering template '{% set t = ( states('sensor.supply_temperature')|float - states('sensor.outside_temperature')|float ) %} {% set u = ( states('sensor.exhaust_temperature')|float - states('sensor.outside_temperature')|float ) %} {{ ( t / u *100 )|round(1) }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 758, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        variables, strict=strict, log_fn=log_fn, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 643, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unknown' when rendering template '{% set t = ( states('sensor.supply_temperature')|float - states('sensor.outside_temperature')|float ) %} {% set u = ( states('sensor.exhaust_temperature')|float - states('sensor.outside_temperature')|float ) %} {{ ( t / u *100 )|round(1) }}' but no default was specified[0m
[31m2025-08-06 10:39:28.691 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template '{% set t = ( states('sensor.supply_temperature')|float - states('sensor.outside_temperature')|float ) %} {% set u = ( states('sensor.exhaust_temperature')|float - states('sensor.outside_temperature')|float ) %} {{ ( t / u *100 )|round(1) }}' but no default was specified') while processing template 'Template<template=({% set t = ( states('sensor.supply_temperature')|float - states('sensor.outside_temperature')|float ) %} {% set u = ( states('sensor.exhaust_temperature')|float - states('sensor.outside_temperature')|float ) %} {{ ( t / u *100 )|round(1) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.sprawnosc_rekuperatora'[0m
[33m2025-08-06 10:39:34.964 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:39:34.966 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[31m2025-08-06 10:39:45.631 ERROR (MainThread) [homeassistant.components.mqtt.entity] Error 'The unit of measurement `%` is not valid together with device class `temperature`' when processing MQTT discovery message topic: 'homeassistant/sensor/ebusd_bai_ModulationTempDesired_value/config', message: '{'unique_id': 'ebusd_bai_ModulationTempDesired_value', 'device': {'identifiers': 'ebusd_bai', 'manufacturer': 'ebusd.eu', 'via_device': 'ebusd', 'sw_version': '25.1', 'suggested_area': 'Heating', 'name': 'ebusd bai'}, 'value_template': '{{value_json["value"].value}}', 'state_topic': 'ebusd/bai/ModulationTempDesired', 'unit_of_measurement': '%', 'state_class': 'measurement', 'device_class': 'temperature', 'name': 'ModulationTempDesired '}'[0m
[31m2025-08-06 10:39:46.153 ERROR (MainThread) [homeassistant.components.mqtt.entity] Error 'The unit of measurement `%` is not valid together with device class `temperature`' when processing MQTT discovery message topic: 'homeassistant/sensor/ebusd_vr_71_Mc1FlowTempDesired_mixermovement/config', message: '{'unique_id': 'ebusd_vr_71_Mc1FlowTempDesired_mixermovement', 'device': {'identifiers': 'ebusd_vr_71', 'manufacturer': 'ebusd.eu', 'via_device': 'ebusd', 'sw_version': '25.1', 'suggested_area': 'Heating', 'name': 'ebusd vr_71'}, 'value_template': '{{value_json["mixermovement"].value}}', 'state_topic': 'ebusd/vr_71/Mc1FlowTempDesired', 'unit_of_measurement': '%', 'state_class': 'measurement', 'device_class': 'temperature', 'name': 'Mc1FlowTempDesired mixermovement'}'[0m
[31m2025-08-06 10:39:46.220 ERROR (MainThread) [homeassistant.components.mqtt.entity] Error 'The unit of measurement `%` is not valid together with device class `temperature`' when processing MQTT discovery message topic: 'homeassistant/sensor/ebusd_vr_71_Mc2FlowTempDesired_mixermovement/config', message: '{'unique_id': 'ebusd_vr_71_Mc2FlowTempDesired_mixermovement', 'device': {'identifiers': 'ebusd_vr_71', 'manufacturer': 'ebusd.eu', 'via_device': 'ebusd', 'sw_version': '25.1', 'suggested_area': 'Heating', 'name': 'ebusd vr_71'}, 'value_template': '{{value_json["mixermovement"].value}}', 'state_topic': 'ebusd/vr_71/Mc2FlowTempDesired', 'unit_of_measurement': '%', 'state_class': 'measurement', 'device_class': 'temperature', 'name': 'Mc2FlowTempDesired mixermovement'}'[0m
[31m2025-08-06 10:39:46.286 ERROR (MainThread) [homeassistant.components.mqtt.entity] Error 'The unit of measurement `%` is not valid together with device class `temperature`' when processing MQTT discovery message topic: 'homeassistant/sensor/ebusd_vr_71_Mc3FlowTempDesired_mixermovement/config', message: '{'unique_id': 'ebusd_vr_71_Mc3FlowTempDesired_mixermovement', 'device': {'identifiers': 'ebusd_vr_71', 'manufacturer': 'ebusd.eu', 'via_device': 'ebusd', 'sw_version': '25.1', 'suggested_area': 'Heating', 'name': 'ebusd vr_71'}, 'value_template': '{{value_json["mixermovement"].value}}', 'state_topic': 'ebusd/vr_71/Mc3FlowTempDesired', 'unit_of_measurement': '%', 'state_class': 'measurement', 'device_class': 'temperature', 'name': 'Mc3FlowTempDesired mixermovement'}'[0m
[33m2025-08-06 10:39:57.338 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 10:39:58.106 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 10:40:34.965 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:40:34.966 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:40:57.339 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 10:40:58.172 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 10:41:34.968 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:41:34.970 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:41:57.417 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 10:41:58.241 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 10:42:34.973 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:42:34.974 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:42:57.435 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 10:42:58.261 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 10:43:34.969 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:43:34.970 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:43:57.488 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 10:43:58.262 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 10:44:19.325 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.13/site-packages/gql/transport/aiohttp.py:92: UserWarning: WARNING: By default, AIOHTTPTransport does not verify ssl certificates. This will be fixed in the next major version. You can set ssl=True to force the ssl certificate verification or ssl=False to disable this warning
  warnings.warn(
[0m
[33m2025-08-06 10:44:34.971 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:44:34.973 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:44:57.541 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 10:44:58.311 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 10:45:34.971 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:45:34.973 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:45:57.608 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 10:45:58.374 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 10:46:34.971 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:46:34.973 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:46:57.629 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 10:46:58.397 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 10:47:34.981 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:47:34.987 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:47:52.682 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_deactivationstemplimiter (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('temperature') it is using; expected one of ['K', '°F', '°C']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-06 10:47:57.682 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 10:47:58.441 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 10:48:34.975 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:48:34.978 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:48:57.696 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 10:48:58.450 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 10:49:34.974 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:49:34.977 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:49:57.717 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 10:49:58.504 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 10:50:22.989 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_prenergycounthc1 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['kWh', 'J', 'Wh', 'GJ', 'Gcal', 'cal', 'TWh', 'kcal', 'MWh', 'mWh', 'MJ', 'kJ', 'Mcal', 'GWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-06 10:50:26.995 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_prenergycounthc2 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['kWh', 'J', 'Wh', 'GJ', 'Gcal', 'cal', 'TWh', 'kcal', 'MWh', 'mWh', 'MJ', 'kJ', 'Mcal', 'GWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-06 10:50:32.045 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_prenergycounthc3 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['kWh', 'J', 'Wh', 'GJ', 'Gcal', 'cal', 'TWh', 'kcal', 'MWh', 'mWh', 'MJ', 'kJ', 'Mcal', 'GWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-06 10:50:34.975 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:50:34.976 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:50:42.165 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_prenergycounthwc1 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['kWh', 'J', 'Wh', 'GJ', 'Gcal', 'cal', 'TWh', 'kcal', 'MWh', 'mWh', 'MJ', 'kJ', 'Mcal', 'GWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-06 10:50:47.213 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_prenergycounthwc2 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['kWh', 'J', 'Wh', 'GJ', 'Gcal', 'cal', 'TWh', 'kcal', 'MWh', 'mWh', 'MJ', 'kJ', 'Mcal', 'GWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-06 10:50:52.261 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_prenergycounthwc3 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['kWh', 'J', 'Wh', 'GJ', 'Gcal', 'cal', 'TWh', 'kcal', 'MWh', 'mWh', 'MJ', 'kJ', 'Mcal', 'GWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-06 10:50:57.309 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_prenergysumhc1 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['kWh', 'J', 'Wh', 'GJ', 'Gcal', 'cal', 'TWh', 'kcal', 'MWh', 'mWh', 'MJ', 'kJ', 'Mcal', 'GWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-06 10:50:57.752 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 10:50:58.526 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 10:51:02.323 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_prenergysumhc2 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['kWh', 'J', 'Wh', 'GJ', 'Gcal', 'cal', 'TWh', 'kcal', 'MWh', 'mWh', 'MJ', 'kJ', 'Mcal', 'GWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-06 10:51:12.346 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_prenergysumhc3 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['kWh', 'J', 'Wh', 'GJ', 'Gcal', 'cal', 'TWh', 'kcal', 'MWh', 'mWh', 'MJ', 'kJ', 'Mcal', 'GWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-06 10:51:17.360 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_prenergysumhwc1 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['kWh', 'J', 'Wh', 'GJ', 'Gcal', 'cal', 'TWh', 'kcal', 'MWh', 'mWh', 'MJ', 'kJ', 'Mcal', 'GWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-06 10:51:22.378 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_prenergysumhwc2 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['kWh', 'J', 'Wh', 'GJ', 'Gcal', 'cal', 'TWh', 'kcal', 'MWh', 'mWh', 'MJ', 'kJ', 'Mcal', 'GWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-06 10:51:27.418 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_prenergysumhwc3 (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('energy') it is using; expected one of ['kWh', 'J', 'Wh', 'GJ', 'Gcal', 'cal', 'TWh', 'kcal', 'MWh', 'mWh', 'MJ', 'kJ', 'Mcal', 'GWh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-06 10:51:34.986 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:51:34.986 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:51:47.516 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_pumppower (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('power') it is using; expected one of ['mW', 'GW', 'MW', 'W', 'kW', 'TW']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-06 10:51:57.818 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 10:51:58.546 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_bai_returntemp_tempmirror (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('temperature') it is using; expected one of ['K', '°F', '°C']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22[0m
[33m2025-08-06 10:51:58.611 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 10:52:34.975 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:52:34.978 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:52:57.827 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 10:52:58.597 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 10:53:34.976 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:53:34.978 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[31m2025-08-06 10:53:57.188 ERROR (MainThread) [homeassistant.components.philips_js.coordinator] Error fetching philips_js data: [0m
[33m2025-08-06 10:53:57.879 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 10:53:58.657 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[31m2025-08-06 10:54:30.342 ERROR (MainThread) [homeassistant.components.analytics] Error sending analytics to https://analytics-api.home-assistant.io/v1: ClientConnectorError(ConnectionKey(host='analytics-api.home-assistant.io', port=443, is_ssl=True, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(111, "Multiple exceptions: [Errno 111] Connect call failed ('0.0.0.0', 443), [Errno 111] Connect call failed ('::', 443, 0, 0)"))[0m
[33m2025-08-06 10:54:34.976 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:54:34.978 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:54:57.941 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 10:54:58.716 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 10:55:34.976 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:55:34.978 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:55:57.963 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 10:55:58.742 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 10:56:34.977 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:56:34.981 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:56:57.970 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 10:56:58.742 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 10:57:34.979 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:57:34.990 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:57:58.026 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 10:57:58.805 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 10:58:34.980 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:58:34.982 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:58:58.098 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 10:58:58.870 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 10:59:34.981 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:59:34.982 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 10:59:58.124 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 10:59:58.914 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:00:00.861 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities switch.grzanie_wody are missing or not currently available[0m
[33m2025-08-06 11:00:34.981 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:00:34.983 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:00:58.184 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:00:58.958 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:01:34.980 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:01:34.982 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:01:58.215 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:01:58.990 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:02:34.981 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:02:34.983 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:02:58.255 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:02:59.033 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:03:34.981 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:03:34.983 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:03:58.277 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:03:59.051 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:04:34.982 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:04:34.994 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:04:58.322 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:04:59.102 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:05:34.981 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:05:34.984 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:05:58.355 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:05:59.135 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:06:34.994 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:06:34.994 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:06:58.369 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:06:59.148 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:07:34.982 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:07:34.983 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:07:58.430 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:07:59.208 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:08:34.985 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:08:34.988 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:08:58.491 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:08:59.271 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:09:32.942 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities switch.podbitka2 are missing or not currently available[0m
[33m2025-08-06 11:09:34.991 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:09:34.992 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:09:58.550 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:09:59.331 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:10:00.861 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities switch.grzanie_wody are missing or not currently available[0m
[33m2025-08-06 11:10:34.986 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:10:34.989 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:10:58.591 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:10:59.371 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:11:34.986 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:11:34.988 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:11:58.655 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:11:59.435 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:12:34.987 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:12:34.989 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:12:58.720 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:12:59.490 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:13:35.002 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:13:35.034 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:13:58.773 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:13:59.552 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:14:34.988 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:14:34.991 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:14:58.813 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:14:59.583 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:15:34.988 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:15:34.990 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:15:58.838 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:15:59.611 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:16:34.989 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:16:34.990 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:16:58.893 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:16:59.671 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:17:34.989 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:17:34.992 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:17:58.931 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:17:59.704 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:18:34.989 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:18:34.993 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:18:58.993 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:18:59.774 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:19:34.990 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:19:34.992 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:19:58.987 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:19:59.769 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:20:34.991 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:20:34.994 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:20:59.049 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:20:59.826 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:21:34.992 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:21:34.994 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:21:59.111 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:21:59.885 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:22:34.992 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:22:34.994 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:22:59.141 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:22:59.921 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:23:34.992 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:23:34.995 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:23:59.206 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:23:59.983 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:24:34.992 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:24:34.993 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:24:59.215 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:24:59.983 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:25:34.992 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:25:34.994 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:25:59.222 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:26:00.005 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:26:34.995 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:26:34.996 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:26:59.291 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:27:00.075 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:27:34.994 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:27:34.995 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:27:59.325 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:28:00.105 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:28:34.994 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:28:34.996 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:28:59.326 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:29:00.106 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:29:34.995 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:29:34.998 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:29:59.343 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:30:00.117 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:30:34.996 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:30:34.998 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:30:59.400 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:31:00.181 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:31:34.997 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:31:34.998 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:31:59.407 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:32:00.183 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:32:34.997 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:32:34.998 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:32:59.464 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:33:00.241 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:33:34.997 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:33:35.000 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:33:59.526 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:34:00.304 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:34:34.997 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:34:34.999 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:34:59.553 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:35:00.339 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:35:34.999 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:35:35.001 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:35:59.618 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:36:00.391 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:36:34.999 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:36:35.001 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:36:59.626 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:37:00.404 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:37:35.000 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:37:35.003 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:37:59.649 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:38:00.423 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:38:35.008 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:38:35.012 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:38:59.689 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:39:00.465 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:39:35.005 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:39:35.006 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:39:59.709 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:40:00.495 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:40:32.943 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities switch.podbitka2 are missing or not currently available[0m
[33m2025-08-06 11:40:35.002 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:40:35.007 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:40:59.769 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:41:00.544 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:41:35.001 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:41:35.004 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:41:59.789 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:42:00.558 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[33m2025-08-06 11:42:21.508 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xtend_tuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:21.509 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration philips_ambilight_hue which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:21.511 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration waste_management which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:21.512 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration satel which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:21.513 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:21.514 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration irrigationprogram which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:21.515 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:21.516 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration edgeos which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:21.518 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:21.519 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dahua which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:21.520 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:21.521 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hikconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:21.522 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:35.005 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:42:35.008 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[31m2025-08-06 11:42:41.332 ERROR (MainThread) [custom_components.hacs] Download failed - Got status code 404 when trying to download https://github.com/blakinio/thesslagreen/archive/refs/heads/c78bc5a.zip
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 709, in async_download_file
    raise HacsException(
    ...<2 lines>...
    )
custom_components.hacs.exceptions.HacsException: Got status code 404 when trying to download https://github.com/blakinio/thesslagreen/archive/refs/heads/c78bc5a.zip[0m
[31m2025-08-06 11:42:41.335 ERROR (MainThread) [custom_components.hacs] [<Integration blakinio/thesslagreen>] Failed to download zipball
Traceback (most recent call last):
  File "/config/custom_components/hacs/repositories/base.py", line 631, in download_content
    await self.download_repository_zip()
  File "/config/custom_components/hacs/repositories/base.py", line 677, in download_repository_zip
    raise HacsException(f"[{self}] Failed to download zipball")
custom_components.hacs.exceptions.HacsException: [<Integration blakinio/thesslagreen>] Failed to download zipball[0m
[33m2025-08-06 11:42:44.862 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration xtend_tuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:44.864 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration philips_ambilight_hue which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:44.865 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration waste_management which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:44.867 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration thessla_green_modbus which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:44.868 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration satel which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:44.869 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:44.870 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration irrigationprogram which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:44.871 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:44.872 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration edgeos which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:44.872 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:44.873 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration dahua which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:44.875 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:44.876 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hikconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:42:44.879 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
s6-rc: info: service legacy-services: stopping
[33m2025-08-06 11:42:59.781 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:43:00.554 WARNING (MainThread) [homeassistant.core] Task <Task pending name='service call background homeassistant.restart' coro=<ServiceRegistry._run_service_call_catch_exceptions() running at /usr/src/homeassistant/homeassistant/core.py:2819> wait_for=<Task pending name='admin service homeassistant.restart' coro=<async_setup.<locals>.async_handle_core_service() running at /usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py:233> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[set.remove(), Task.task_wakeup()]> cb=[set.remove()]> was still running after final writes shutdown stage; Integrations should cancel non-critical tasks when receiving the stop event to prevent delaying shutdown[0m
[33m2025-08-06 11:43:00.561 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
Found 3 non-daemonic threads.
[09:43:16] INFO: [32mHome Assistant Core finish process exit code 0[0m
[09:43:16] INFO: [32mHome Assistant Core service shutdown[0m
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun home-assistant (no readiness notification)
s6-rc: info: service legacy-services successfully started
[33m2025-08-06 11:43:39.286 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xtend_tuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:43:39.289 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration philips_ambilight_hue which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:43:39.289 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration waste_management which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:43:39.290 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration thessla_green_modbus which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:43:39.291 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration satel which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:43:39.291 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:43:39.293 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration irrigationprogram which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:43:39.294 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:43:39.294 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration edgeos which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:43:39.296 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:43:39.297 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dahua which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:43:39.298 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:43:39.299 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hikconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:43:39.300 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2025-08-06 11:43:50.721 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/aiomusiccast/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
[0m
[32m2025-08-06 11:43:51.800 INFO (MainThread) [custom_components.thessla_green_modbus] Setting up ThesslaGreen Modbus integration (Enhanced v2.0)[0m
[36m2025-08-06 11:43:51.801 DEBUG (MainThread) [custom_components.thessla_green_modbus] Configuration: host=192.168.3.17, port=8899, slave_id=10, scan_interval=30, timeout=10, retry=3[0m
[32m2025-08-06 11:43:51.801 INFO (MainThread) [custom_components.thessla_green_modbus] Scanning device capabilities...[0m
[36m2025-08-06 11:43:51.801 DEBUG (MainThread) [custom_components.thessla_green_modbus.device_scanner] Initialized device scanner for 192.168.3.17:8899 (slave_id=10)[0m
[32m2025-08-06 11:43:51.801 INFO (MainThread) [custom_components.thessla_green_modbus.device_scanner] Connected to 192.168.3.17:8899, starting enhanced capability scan...[0m
[36m2025-08-06 11:43:51.806 DEBUG (SyncWorker_2) [pymodbus.logging] Connection to Modbus server established. Socket ('192.168.1.83', 45752)[0m
[36m2025-08-06 11:43:51.807 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Connected to Modbus device, scanning registers...[0m
[36m2025-08-06 11:43:51.916 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x1 0x0 0x0 0x0 0x11 0xa 0x4 0xe 0x0 0xbe 0x0 0xc6 0x0 0xfb 0x0 0xc2 0x80 0x0 0x80 0x0 0x1 0xd[0m
[36m2025-08-06 11:43:51.916 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(4 sub -1) -> ReadInputRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[190, 198, 251, 194, 32768, 32768, 269], status=1) [0m
[36m2025-08-06 11:43:51.916 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:43:51.916 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Input register batch 16-22: 7 registers found[0m
[33m2025-08-06 11:43:51.926 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.13/site-packages/gql/transport/aiohttp.py:92: UserWarning: WARNING: By default, AIOHTTPTransport does not verify ssl certificates. This will be fixed in the next major version. You can set ssl=True to force the ssl certificate verification or ssl=False to disable this warning
  warnings.warn(
[0m
[36m2025-08-06 11:43:52.077 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x2 0x0 0x0 0x0 0x3 0xa 0x84 0x2[0m
[36m2025-08-06 11:43:52.077 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:43:52.078 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Input register batch 32-35 failed: ExceptionResponse(dev_id=10, function_code=132, exception_code=2)[0m
[36m2025-08-06 11:43:52.258 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x3 0x0 0x0 0x0 0x3 0xa 0x84 0x2[0m
[36m2025-08-06 11:43:52.258 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:43:52.258 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Input register batch 48-51 failed: ExceptionResponse(dev_id=10, function_code=132, exception_code=2)[0m
[36m2025-08-06 11:43:52.439 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x4 0x0 0x0 0x0 0x3 0xa 0x84 0x2[0m
[36m2025-08-06 11:43:52.440 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:43:52.440 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Input register batch 64-68 failed: ExceptionResponse(dev_id=10, function_code=132, exception_code=2)[0m
[36m2025-08-06 11:43:52.620 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x5 0x0 0x0 0x0 0x3 0xa 0x84 0x2[0m
[36m2025-08-06 11:43:52.621 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:43:52.621 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Input register batch 80-83 failed: ExceptionResponse(dev_id=10, function_code=132, exception_code=2)[0m
[36m2025-08-06 11:43:52.813 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x6 0x0 0x0 0x0 0x3 0xa 0x84 0x2[0m
[36m2025-08-06 11:43:52.814 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:43:52.814 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Input register batch 96-99 failed: ExceptionResponse(dev_id=10, function_code=132, exception_code=2)[0m
[36m2025-08-06 11:43:53.002 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x7 0x0 0x0 0x0 0x3 0xa 0x84 0x2[0m
[36m2025-08-06 11:43:53.002 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:43:53.002 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Input register batch 112-114 failed: ExceptionResponse(dev_id=10, function_code=132, exception_code=2)[0m
[36m2025-08-06 11:43:53.179 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x8 0x0 0x0 0x0 0x3 0xa 0x84 0x2[0m
[36m2025-08-06 11:43:53.179 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:43:53.179 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Input register batch 128-130 failed: ExceptionResponse(dev_id=10, function_code=132, exception_code=2)[0m
[32m2025-08-06 11:43:53.179 INFO (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Input registers scan: 7 registers found[0m
[36m2025-08-06 11:43:53.383 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x9 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x0 0x0 0x0 0x0 0x1 0x0 0x0[0m
[36m2025-08-06 11:43:53.384 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 1, 0], status=1) [0m
[36m2025-08-06 11:43:53.384 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:43:53.384 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Holding register batch 4096-4099: 4 registers found[0m
[36m2025-08-06 11:43:53.555 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0xa 0x0 0x0 0x0 0x9 0xa 0x3 0x6 0xd 0xcd 0xe 0xd 0x8 0x0[0m
[36m2025-08-06 11:43:53.555 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[3533, 3597, 2048], status=1) [0m
[36m2025-08-06 11:43:53.555 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:43:53.555 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Holding register batch 4112-4114: 3 registers found[0m
[36m2025-08-06 11:43:54.071 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0xb 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:43:54.071 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 0, 0], status=1) [0m
[36m2025-08-06 11:43:54.071 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:43:54.071 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Holding register batch 4128-4131: 4 registers found[0m
[36m2025-08-06 11:43:54.304 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0xc 0x0 0x0 0x0 0xd 0xa 0x3 0xa 0x0 0x8 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:43:54.304 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[8, 0, 0, 0, 0], status=1) [0m
[36m2025-08-06 11:43:54.304 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:43:54.304 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Holding register batch 4144-4148: 5 registers found[0m
[36m2025-08-06 11:43:54.506 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0xd 0x0 0x0 0x0 0x9 0xa 0x3 0x6 0x0 0x5 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:43:54.506 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[5, 0, 0], status=1) [0m
[36m2025-08-06 11:43:54.506 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:43:54.506 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Holding register batch 4160-4162: 3 registers found[0m
[36m2025-08-06 11:43:54.694 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0xe 0x0 0x0 0x0 0xd 0xa 0x3 0xa 0x0 0x8 0x0 0x2 0x0 0x5 0x0 0x5 0x0 0x64[0m
[36m2025-08-06 11:43:54.695 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[8, 2, 5, 5, 100], status=1) [0m
[36m2025-08-06 11:43:54.695 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:43:54.695 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Holding register batch 4176-4180: 5 registers found[0m
[36m2025-08-06 11:43:54.878 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0xf 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:43:54.878 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 0, 0], status=1) [0m
[36m2025-08-06 11:43:54.878 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:43:54.878 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Holding register batch 4192-4195: 4 registers found[0m
[36m2025-08-06 11:43:55.046 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x10 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x1 0x0 0x0 0x0 0x1e 0x0 0x50[0m
[36m2025-08-06 11:43:55.046 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[1, 0, 30, 80], status=1) [0m
[36m2025-08-06 11:43:55.046 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:43:55.046 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Holding register batch 4208-4211: 4 registers found[0m
[32m2025-08-06 11:43:55.047 INFO (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Holding registers scan: 32 registers found[0m
[36m2025-08-06 11:43:55.209 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x11 0x0 0x0 0x0 0x3 0xa 0x81 0x2[0m
[36m2025-08-06 11:43:55.210 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:43:55.389 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x12 0x0 0x0 0x0 0x3 0xa 0x81 0x2[0m
[36m2025-08-06 11:43:55.389 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:43:55.570 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x13 0x0 0x0 0x0 0x3 0xa 0x81 0x2[0m
[36m2025-08-06 11:43:55.570 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[32m2025-08-06 11:43:55.570 INFO (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Coil registers scan: 0 registers found[0m
[36m2025-08-06 11:43:55.768 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x14 0x0 0x0 0x0 0x3 0xa 0x82 0x2[0m
[36m2025-08-06 11:43:55.768 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:43:56.507 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x15 0x0 0x0 0x0 0x3 0xa 0x82 0x2[0m
[36m2025-08-06 11:43:56.507 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:43:56.685 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x16 0x0 0x0 0x0 0x3 0xa 0x82 0x2[0m
[36m2025-08-06 11:43:56.685 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:43:56.870 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x17 0x0 0x0 0x0 0x3 0xa 0x82 0x2[0m
[36m2025-08-06 11:43:56.870 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[32m2025-08-06 11:43:56.870 INFO (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Discrete inputs scan: 0 registers found[0m
[36m2025-08-06 11:43:56.870 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Device info extracted: {'device_name': 'ThesslaGreen AirPack (192.168.3.17)', 'manufacturer': 'ThesslaGreen', 'model': 'AirPack Home', 'firmware': 'Unknown', 'serial_number': None}[0m
[32m2025-08-06 11:43:56.871 INFO (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Capability analysis: 9 capabilities detected[0m
[36m2025-08-06 11:43:56.871 DEBUG (SyncWorker_2) [custom_components.thessla_green_modbus.device_scanner] Detected capabilities: ['basic_control', 'intensity_control', 'temperature_control', 'special_functions', 'gwc_support', 'bypass_support', 'constant_flow', 'comfort_mode', 'advanced_configuration'][0m
[32m2025-08-06 11:43:56.879 INFO (MainThread) [custom_components.thessla_green_modbus.device_scanner] Enhanced scan completed: 39 registers found (39.1% success rate), 9 capabilities detected[0m
[32m2025-08-06 11:43:56.880 INFO (MainThread) [custom_components.thessla_green_modbus] Device scan completed: 7 input registers, 32 holding registers, 9 capabilities[0m
[36m2025-08-06 11:43:56.880 DEBUG (MainThread) [custom_components.thessla_green_modbus.coordinator] Initializing optimized register groups for batch reading...[0m
[36m2025-08-06 11:43:56.880 DEBUG (MainThread) [custom_components.thessla_green_modbus.coordinator] Optimized input_registers: 7 registers grouped into 1 batches[0m
[36m2025-08-06 11:43:56.880 DEBUG (MainThread) [custom_components.thessla_green_modbus.coordinator] Optimized holding_registers: 32 registers grouped into 8 batches[0m
[32m2025-08-06 11:43:56.880 INFO (MainThread) [custom_components.thessla_green_modbus.coordinator] Enhanced coordinator initialized: 192.168.3.17:8899 (slave_id=10, interval=30s, timeout=10s)[0m
[32m2025-08-06 11:43:56.880 INFO (MainThread) [custom_components.thessla_green_modbus] Performing initial data fetch...[0m
[36m2025-08-06 11:43:56.899 DEBUG (SyncWorker_5) [pymodbus.logging] Connection to Modbus server established. Socket ('192.168.1.83', 44746)[0m
[31m2025-08-06 11:43:56.969 ERROR (MainThread) [homeassistant.components.sensor] hikconnect: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 788, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1303, in async_device_update
    await self.async_update()
  File "/config/custom_components/hikconnect/sensor.py", line 64, in async_update
    res = await asyncio.wait_for(get_call_status_coro, SCAN_INTERVAL_TIMEOUT.seconds)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hikconnect/api.py", line 233, in get_call_status
    raise DeviceOffline()
hikconnect.exceptions.DeviceOffline[0m
[31m2025-08-06 11:43:57.356 ERROR (MainThread) [homeassistant.components.sensor] hikconnect: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 788, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1303, in async_device_update
    await self.async_update()
  File "/config/custom_components/hikconnect/sensor.py", line 64, in async_update
    res = await asyncio.wait_for(get_call_status_coro, SCAN_INTERVAL_TIMEOUT.seconds)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hikconnect/api.py", line 233, in get_call_status
    raise DeviceOffline()
hikconnect.exceptions.DeviceOffline[0m
[33m2025-08-06 11:43:58.243 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.29.5 is exactly one major version older than the runtime version 6.31.1 at api.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
[0m
[33m2025-08-06 11:43:58.245 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.29.5 is exactly one major version older than the runtime version 6.31.1 at api_options.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
[0m
[36m2025-08-06 11:44:07.076 DEBUG (SyncWorker_5) [pymodbus.logging] Processing: 0x0 0x1 0x0 0x0 0x0 0x11 0xa 0x4 0xe 0x0 0xbf 0x0 0xc6 0x0 0xfb 0x0 0xc2 0x80 0x0 0x80 0x0 0x1 0xd[0m
[36m2025-08-06 11:44:07.076 DEBUG (SyncWorker_5) [pymodbus.logging] decoded PDU function_code(4 sub -1) -> ReadInputRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[191, 198, 251, 194, 32768, 32768, 269], status=1) [0m
[36m2025-08-06 11:44:07.076 DEBUG (SyncWorker_5) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:44:07.221 DEBUG (SyncWorker_5) [pymodbus.logging] Processing: 0x0 0x2 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x0 0x0 0x0 0x0 0x1 0x0 0x0[0m
[36m2025-08-06 11:44:07.221 DEBUG (SyncWorker_5) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 1, 0], status=1) [0m
[36m2025-08-06 11:44:07.222 DEBUG (SyncWorker_5) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:44:07.401 DEBUG (SyncWorker_5) [pymodbus.logging] Processing: 0x0 0x3 0x0 0x0 0x0 0x9 0xa 0x3 0x6 0xd 0xcd 0xe 0xd 0x8 0x0[0m
[36m2025-08-06 11:44:07.402 DEBUG (SyncWorker_5) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[3533, 3597, 2048], status=1) [0m
[36m2025-08-06 11:44:07.402 DEBUG (SyncWorker_5) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:44:07.602 DEBUG (SyncWorker_5) [pymodbus.logging] Processing: 0x0 0x4 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:44:07.602 DEBUG (SyncWorker_5) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 0, 0], status=1) [0m
[36m2025-08-06 11:44:07.602 DEBUG (SyncWorker_5) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:44:07.797 DEBUG (SyncWorker_5) [pymodbus.logging] Processing: 0x0 0x5 0x0 0x0 0x0 0xd 0xa 0x3 0xa 0x0 0x8 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:44:07.797 DEBUG (SyncWorker_5) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[8, 0, 0, 0, 0], status=1) [0m
[36m2025-08-06 11:44:07.798 DEBUG (SyncWorker_5) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:44:07.967 DEBUG (SyncWorker_5) [pymodbus.logging] Processing: 0x0 0x6 0x0 0x0 0x0 0x9 0xa 0x3 0x6 0x0 0x5 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:44:07.968 DEBUG (SyncWorker_5) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[5, 0, 0], status=1) [0m
[36m2025-08-06 11:44:07.968 DEBUG (SyncWorker_5) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:44:08.169 DEBUG (SyncWorker_5) [pymodbus.logging] Processing: 0x0 0x7 0x0 0x0 0x0 0xd 0xa 0x3 0xa 0x0 0x8 0x0 0x2 0x0 0x5 0x0 0x5 0x0 0x64[0m
[36m2025-08-06 11:44:08.169 DEBUG (SyncWorker_5) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[8, 2, 5, 5, 100], status=1) [0m
[36m2025-08-06 11:44:08.169 DEBUG (SyncWorker_5) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:44:08.338 DEBUG (SyncWorker_5) [pymodbus.logging] Processing: 0x0 0x8 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:44:08.338 DEBUG (SyncWorker_5) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 0, 0], status=1) [0m
[36m2025-08-06 11:44:08.338 DEBUG (SyncWorker_5) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:44:08.519 DEBUG (SyncWorker_5) [pymodbus.logging] Processing: 0x0 0x9 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x1 0x0 0x0 0x0 0x1e 0x0 0x50[0m
[36m2025-08-06 11:44:08.519 DEBUG (SyncWorker_5) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[1, 0, 30, 80], status=1) [0m
[36m2025-08-06 11:44:08.519 DEBUG (SyncWorker_5) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:44:08.521 DEBUG (MainThread) [custom_components.thessla_green_modbus.coordinator] Data update completed in 11.64s (avg: 11.64s, success rate: 100.0%)[0m
[36m2025-08-06 11:44:08.521 DEBUG (MainThread) [custom_components.thessla_green_modbus.coordinator] Finished fetching thessla_green_modbus data in 11.640 seconds (success: True)[0m
[32m2025-08-06 11:44:08.521 INFO (MainThread) [custom_components.thessla_green_modbus] Initial data fetch completed successfully[0m
[32m2025-08-06 11:44:08.522 INFO (MainThread) [custom_components.thessla_green_modbus] Setting up platforms...[0m
[36m2025-08-06 11:44:08.587 DEBUG (MainThread) [custom_components.thessla_green_modbus.sensor] Adding 7 enhanced sensor entities[0m
[36m2025-08-06 11:44:08.591 DEBUG (MainThread) [custom_components.thessla_green_modbus.select] Adding 8 enhanced select entities[0m
[36m2025-08-06 11:44:08.596 DEBUG (MainThread) [custom_components.thessla_green_modbus.number] Adding 12 enhanced number entities[0m
[36m2025-08-06 11:44:08.601 DEBUG (MainThread) [custom_components.thessla_green_modbus.climate] Adding 1 enhanced climate entities[0m
[36m2025-08-06 11:44:08.602 DEBUG (MainThread) [custom_components.thessla_green_modbus.fan] Adding 1 enhanced fan entities[0m
[36m2025-08-06 11:44:08.604 DEBUG (MainThread) [custom_components.thessla_green_modbus] Registering ThesslaGreen services[0m
[36m2025-08-06 11:44:08.605 DEBUG (MainThread) [custom_components.thessla_green_modbus] Registered 9 ThesslaGreen services[0m
[32m2025-08-06 11:44:08.605 INFO (MainThread) [custom_components.thessla_green_modbus] ThesslaGreen Modbus integration setup completed successfully[0m
[31m2025-08-06 11:44:11.144 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({% set t = ( states('sensor.supply_temperature')|float - states('sensor.outside_temperature')|float ) %} {% set u = ( states('sensor.exhaust_temperature')|float - states('sensor.outside_temperature')|float ) %} {{ ( t / u *100 )|round(1) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2446, in forgiving_float_filter
    return float(value)
ValueError: could not convert string to float: 'unknown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 641, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2977, in _render_with_context
    return template.render(**kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2449, in forgiving_float_filter
    raise_no_default("float", value)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1975, in raise_no_default
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Template error: float got invalid input 'unknown' when rendering template '{% set t = ( states('sensor.supply_temperature')|float - states('sensor.outside_temperature')|float ) %} {% set u = ( states('sensor.exhaust_temperature')|float - states('sensor.outside_temperature')|float ) %} {{ ( t / u *100 )|round(1) }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 758, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        variables, strict=strict, log_fn=log_fn, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 643, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unknown' when rendering template '{% set t = ( states('sensor.supply_temperature')|float - states('sensor.outside_temperature')|float ) %} {% set u = ( states('sensor.exhaust_temperature')|float - states('sensor.outside_temperature')|float ) %} {{ ( t / u *100 )|round(1) }}' but no default was specified[0m
[31m2025-08-06 11:44:11.153 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template '{% set t = ( states('sensor.supply_temperature')|float - states('sensor.outside_temperature')|float ) %} {% set u = ( states('sensor.exhaust_temperature')|float - states('sensor.outside_temperature')|float ) %} {{ ( t / u *100 )|round(1) }}' but no default was specified') while processing template 'Template<template=({% set t = ( states('sensor.supply_temperature')|float - states('sensor.outside_temperature')|float ) %} {% set u = ( states('sensor.exhaust_temperature')|float - states('sensor.outside_temperature')|float ) %} {{ ( t / u *100 )|round(1) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.sprawnosc_rekuperatora'[0m
[31m2025-08-06 11:44:34.372 ERROR (MainThread) [homeassistant.components.mqtt.entity] Error 'The unit of measurement `%` is not valid together with device class `temperature`' when processing MQTT discovery message topic: 'homeassistant/sensor/ebusd_bai_ModulationTempDesired_value/config', message: '{'unique_id': 'ebusd_bai_ModulationTempDesired_value', 'device': {'identifiers': 'ebusd_bai', 'manufacturer': 'ebusd.eu', 'via_device': 'ebusd', 'sw_version': '25.1', 'suggested_area': 'Heating', 'name': 'ebusd bai'}, 'value_template': '{{value_json["value"].value}}', 'state_topic': 'ebusd/bai/ModulationTempDesired', 'unit_of_measurement': '%', 'state_class': 'measurement', 'device_class': 'temperature', 'name': 'ModulationTempDesired '}'[0m
[31m2025-08-06 11:44:34.951 ERROR (MainThread) [homeassistant.components.mqtt.entity] Error 'The unit of measurement `%` is not valid together with device class `temperature`' when processing MQTT discovery message topic: 'homeassistant/sensor/ebusd_vr_71_Mc1FlowTempDesired_mixermovement/config', message: '{'unique_id': 'ebusd_vr_71_Mc1FlowTempDesired_mixermovement', 'device': {'identifiers': 'ebusd_vr_71', 'manufacturer': 'ebusd.eu', 'via_device': 'ebusd', 'sw_version': '25.1', 'suggested_area': 'Heating', 'name': 'ebusd vr_71'}, 'value_template': '{{value_json["mixermovement"].value}}', 'state_topic': 'ebusd/vr_71/Mc1FlowTempDesired', 'unit_of_measurement': '%', 'state_class': 'measurement', 'device_class': 'temperature', 'name': 'Mc1FlowTempDesired mixermovement'}'[0m
[31m2025-08-06 11:44:35.018 ERROR (MainThread) [homeassistant.components.mqtt.entity] Error 'The unit of measurement `%` is not valid together with device class `temperature`' when processing MQTT discovery message topic: 'homeassistant/sensor/ebusd_vr_71_Mc2FlowTempDesired_mixermovement/config', message: '{'unique_id': 'ebusd_vr_71_Mc2FlowTempDesired_mixermovement', 'device': {'identifiers': 'ebusd_vr_71', 'manufacturer': 'ebusd.eu', 'via_device': 'ebusd', 'sw_version': '25.1', 'suggested_area': 'Heating', 'name': 'ebusd vr_71'}, 'value_template': '{{value_json["mixermovement"].value}}', 'state_topic': 'ebusd/vr_71/Mc2FlowTempDesired', 'unit_of_measurement': '%', 'state_class': 'measurement', 'device_class': 'temperature', 'name': 'Mc2FlowTempDesired mixermovement'}'[0m
[33m2025-08-06 11:44:35.033 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:44:35.035 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[31m2025-08-06 11:44:35.044 ERROR (MainThread) [homeassistant.components.mqtt.entity] Error 'The unit of measurement `%` is not valid together with device class `temperature`' when processing MQTT discovery message topic: 'homeassistant/sensor/ebusd_vr_71_Mc3FlowTempDesired_mixermovement/config', message: '{'unique_id': 'ebusd_vr_71_Mc3FlowTempDesired_mixermovement', 'device': {'identifiers': 'ebusd_vr_71', 'manufacturer': 'ebusd.eu', 'via_device': 'ebusd', 'sw_version': '25.1', 'suggested_area': 'Heating', 'name': 'ebusd vr_71'}, 'value_template': '{{value_json["mixermovement"].value}}', 'state_topic': 'ebusd/vr_71/Mc3FlowTempDesired', 'unit_of_measurement': '%', 'state_class': 'measurement', 'device_class': 'temperature', 'name': 'Mc3FlowTempDesired mixermovement'}'[0m
[36m2025-08-06 11:44:38.424 DEBUG (SyncWorker_2) [pymodbus.logging] Connection to Modbus server established. Socket ('192.168.1.83', 43076)[0m
[36m2025-08-06 11:44:48.628 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x1 0x0 0x0 0x0 0x11 0xa 0x4 0xe 0x0 0xbf 0x0 0xc7 0x0 0xfb 0x0 0xc4 0x80 0x0 0x80 0x0 0x1 0xd[0m
[36m2025-08-06 11:44:48.629 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(4 sub -1) -> ReadInputRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[191, 199, 251, 196, 32768, 32768, 269], status=1) [0m
[36m2025-08-06 11:44:48.629 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:44:48.805 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x2 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x0 0x0 0x0 0x0 0x1 0x0 0x0[0m
[36m2025-08-06 11:44:48.805 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 1, 0], status=1) [0m
[36m2025-08-06 11:44:48.805 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:44:49.000 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x3 0x0 0x0 0x0 0x9 0xa 0x3 0x6 0xd 0xcd 0xe 0xd 0x8 0x0[0m
[36m2025-08-06 11:44:49.001 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[3533, 3597, 2048], status=1) [0m
[36m2025-08-06 11:44:49.001 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:44:49.193 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x4 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:44:49.193 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 0, 0], status=1) [0m
[36m2025-08-06 11:44:49.193 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:44:49.369 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x5 0x0 0x0 0x0 0xd 0xa 0x3 0xa 0x0 0x8 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:44:49.370 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[8, 0, 0, 0, 0], status=1) [0m
[36m2025-08-06 11:44:49.370 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:44:49.564 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x6 0x0 0x0 0x0 0x9 0xa 0x3 0x6 0x0 0x5 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:44:49.564 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[5, 0, 0], status=1) [0m
[36m2025-08-06 11:44:49.564 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:44:49.742 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x7 0x0 0x0 0x0 0xd 0xa 0x3 0xa 0x0 0x8 0x0 0x2 0x0 0x5 0x0 0x5 0x0 0x64[0m
[36m2025-08-06 11:44:49.742 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[8, 2, 5, 5, 100], status=1) [0m
[36m2025-08-06 11:44:49.742 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:44:49.918 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x8 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:44:49.918 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 0, 0], status=1) [0m
[36m2025-08-06 11:44:49.918 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:44:50.100 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x9 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x1 0x0 0x0 0x0 0x1e 0x0 0x50[0m
[36m2025-08-06 11:44:50.101 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[1, 0, 30, 80], status=1) [0m
[36m2025-08-06 11:44:50.101 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:44:50.102 DEBUG (MainThread) [custom_components.thessla_green_modbus.coordinator] Data update completed in 11.70s (avg: 11.67s, success rate: 100.0%)[0m
[36m2025-08-06 11:44:50.102 DEBUG (MainThread) [custom_components.thessla_green_modbus.coordinator] Finished fetching thessla_green_modbus data in 11.697 seconds (success: True)[0m
[33m2025-08-06 11:44:59.862 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:45:00.642 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[36m2025-08-06 11:45:20.411 DEBUG (SyncWorker_7) [pymodbus.logging] Connection to Modbus server established. Socket ('192.168.1.83', 49002)[0m
[36m2025-08-06 11:45:30.597 DEBUG (SyncWorker_7) [pymodbus.logging] Processing: 0x0 0x1 0x0 0x0 0x0 0x11 0xa 0x4 0xe 0x0 0xbf 0x0 0xc7 0x0 0xfb 0x0 0xc4 0x80 0x0 0x80 0x0 0x1 0xd[0m
[36m2025-08-06 11:45:30.597 DEBUG (SyncWorker_7) [pymodbus.logging] decoded PDU function_code(4 sub -1) -> ReadInputRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[191, 199, 251, 196, 32768, 32768, 269], status=1) [0m
[36m2025-08-06 11:45:30.598 DEBUG (SyncWorker_7) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:45:30.765 DEBUG (SyncWorker_7) [pymodbus.logging] Processing: 0x0 0x2 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x0 0x0 0x0 0x0 0x1 0x0 0x0[0m
[36m2025-08-06 11:45:30.765 DEBUG (SyncWorker_7) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 1, 0], status=1) [0m
[36m2025-08-06 11:45:30.765 DEBUG (SyncWorker_7) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:45:30.962 DEBUG (SyncWorker_7) [pymodbus.logging] Processing: 0x0 0x3 0x0 0x0 0x0 0x9 0xa 0x3 0x6 0xd 0xcd 0xe 0xd 0x8 0x0[0m
[36m2025-08-06 11:45:30.962 DEBUG (SyncWorker_7) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[3533, 3597, 2048], status=1) [0m
[36m2025-08-06 11:45:30.962 DEBUG (SyncWorker_7) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:45:31.136 DEBUG (SyncWorker_7) [pymodbus.logging] Processing: 0x0 0x4 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:45:31.136 DEBUG (SyncWorker_7) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 0, 0], status=1) [0m
[36m2025-08-06 11:45:31.136 DEBUG (SyncWorker_7) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:45:31.318 DEBUG (SyncWorker_7) [pymodbus.logging] Processing: 0x0 0x5 0x0 0x0 0x0 0xd 0xa 0x3 0xa 0x0 0x8 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:45:31.319 DEBUG (SyncWorker_7) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[8, 0, 0, 0, 0], status=1) [0m
[36m2025-08-06 11:45:31.319 DEBUG (SyncWorker_7) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:45:31.496 DEBUG (SyncWorker_7) [pymodbus.logging] Processing: 0x0 0x6 0x0 0x0 0x0 0x9 0xa 0x3 0x6 0x0 0x5 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:45:31.496 DEBUG (SyncWorker_7) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[5, 0, 0], status=1) [0m
[36m2025-08-06 11:45:31.496 DEBUG (SyncWorker_7) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:45:31.682 DEBUG (SyncWorker_7) [pymodbus.logging] Processing: 0x0 0x7 0x0 0x0 0x0 0xd 0xa 0x3 0xa 0x0 0x8 0x0 0x2 0x0 0x5 0x0 0x5 0x0 0x64[0m
[36m2025-08-06 11:45:31.683 DEBUG (SyncWorker_7) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[8, 2, 5, 5, 100], status=1) [0m
[36m2025-08-06 11:45:31.683 DEBUG (SyncWorker_7) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:45:31.880 DEBUG (SyncWorker_7) [pymodbus.logging] Processing: 0x0 0x8 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:45:31.880 DEBUG (SyncWorker_7) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 0, 0], status=1) [0m
[36m2025-08-06 11:45:31.880 DEBUG (SyncWorker_7) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:45:32.070 DEBUG (SyncWorker_7) [pymodbus.logging] Processing: 0x0 0x9 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x1 0x0 0x0 0x0 0x1e 0x0 0x50[0m
[36m2025-08-06 11:45:32.070 DEBUG (SyncWorker_7) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[1, 0, 30, 80], status=1) [0m
[36m2025-08-06 11:45:32.070 DEBUG (SyncWorker_7) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:45:32.071 DEBUG (MainThread) [custom_components.thessla_green_modbus.coordinator] Data update completed in 11.67s (avg: 11.67s, success rate: 100.0%)[0m
[36m2025-08-06 11:45:32.071 DEBUG (MainThread) [custom_components.thessla_green_modbus.coordinator] Finished fetching thessla_green_modbus data in 11.666 seconds (success: True)[0m
[33m2025-08-06 11:45:35.008 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:45:35.011 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:45:59.886 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:46:00.660 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[36m2025-08-06 11:46:02.409 DEBUG (SyncWorker_2) [pymodbus.logging] Connection to Modbus server established. Socket ('192.168.1.83', 33534)[0m
[36m2025-08-06 11:46:12.549 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x1 0x0 0x0 0x0 0x11 0xa 0x4 0xe 0x0 0xbf 0x0 0xc7 0x0 0xfb 0x0 0xc4 0x80 0x0 0x80 0x0 0x1 0xd[0m
[36m2025-08-06 11:46:12.550 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(4 sub -1) -> ReadInputRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[191, 199, 251, 196, 32768, 32768, 269], status=1) [0m
[36m2025-08-06 11:46:12.550 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:46:12.724 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x2 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x0 0x0 0x0 0x0 0x1 0x0 0x0[0m
[36m2025-08-06 11:46:12.724 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 1, 0], status=1) [0m
[36m2025-08-06 11:46:12.724 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:46:12.903 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x3 0x0 0x0 0x0 0x9 0xa 0x3 0x6 0xd 0xcd 0xe 0xd 0x8 0x0[0m
[36m2025-08-06 11:46:12.903 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[3533, 3597, 2048], status=1) [0m
[36m2025-08-06 11:46:12.903 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:46:13.088 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x4 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:46:13.088 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 0, 0], status=1) [0m
[36m2025-08-06 11:46:13.088 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:46:13.288 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x5 0x0 0x0 0x0 0xd 0xa 0x3 0xa 0x0 0x8 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:46:13.288 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[8, 0, 0, 0, 0], status=1) [0m
[36m2025-08-06 11:46:13.288 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:46:13.475 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x6 0x0 0x0 0x0 0x9 0xa 0x3 0x6 0x0 0x5 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:46:13.475 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[5, 0, 0], status=1) [0m
[36m2025-08-06 11:46:13.475 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:46:13.653 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x7 0x0 0x0 0x0 0xd 0xa 0x3 0xa 0x0 0x8 0x0 0x2 0x0 0x5 0x0 0x5 0x0 0x64[0m
[36m2025-08-06 11:46:13.653 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[8, 2, 5, 5, 100], status=1) [0m
[36m2025-08-06 11:46:13.653 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:46:13.849 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x8 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:46:13.850 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 0, 0], status=1) [0m
[36m2025-08-06 11:46:13.850 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:46:14.022 DEBUG (SyncWorker_2) [pymodbus.logging] Processing: 0x0 0x9 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x1 0x0 0x0 0x0 0x1e 0x0 0x50[0m
[36m2025-08-06 11:46:14.022 DEBUG (SyncWorker_2) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[1, 0, 30, 80], status=1) [0m
[36m2025-08-06 11:46:14.022 DEBUG (SyncWorker_2) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:46:14.032 DEBUG (MainThread) [custom_components.thessla_green_modbus.coordinator] Data update completed in 11.63s (avg: 11.66s, success rate: 100.0%)[0m
[36m2025-08-06 11:46:14.032 DEBUG (MainThread) [custom_components.thessla_green_modbus.coordinator] Finished fetching thessla_green_modbus data in 11.626 seconds (success: True)[0m
[33m2025-08-06 11:46:35.008 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:46:35.010 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[36m2025-08-06 11:46:44.410 DEBUG (SyncWorker_6) [pymodbus.logging] Connection to Modbus server established. Socket ('192.168.1.83', 54318)[0m
[36m2025-08-06 11:46:54.507 DEBUG (SyncWorker_6) [pymodbus.logging] Processing: 0x0 0x1 0x0 0x0 0x0 0x11 0xa 0x4 0xe 0x0 0xbf 0x0 0xc7 0x0 0xfb 0x0 0xc3 0x80 0x0 0x80 0x0 0x1 0xd[0m
[36m2025-08-06 11:46:54.507 DEBUG (SyncWorker_6) [pymodbus.logging] decoded PDU function_code(4 sub -1) -> ReadInputRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[191, 199, 251, 195, 32768, 32768, 269], status=1) [0m
[36m2025-08-06 11:46:54.507 DEBUG (SyncWorker_6) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:46:54.699 DEBUG (SyncWorker_6) [pymodbus.logging] Processing: 0x0 0x2 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x0 0x0 0x0 0x0 0x1 0x0 0x0[0m
[36m2025-08-06 11:46:54.699 DEBUG (SyncWorker_6) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 1, 0], status=1) [0m
[36m2025-08-06 11:46:54.699 DEBUG (SyncWorker_6) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:46:54.887 DEBUG (SyncWorker_6) [pymodbus.logging] Processing: 0x0 0x3 0x0 0x0 0x0 0x9 0xa 0x3 0x6 0xd 0xcd 0xe 0xd 0x8 0x0[0m
[36m2025-08-06 11:46:54.887 DEBUG (SyncWorker_6) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[3533, 3597, 2048], status=1) [0m
[36m2025-08-06 11:46:54.888 DEBUG (SyncWorker_6) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:46:55.063 DEBUG (SyncWorker_6) [pymodbus.logging] Processing: 0x0 0x4 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:46:55.063 DEBUG (SyncWorker_6) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 0, 0], status=1) [0m
[36m2025-08-06 11:46:55.063 DEBUG (SyncWorker_6) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:46:55.265 DEBUG (SyncWorker_6) [pymodbus.logging] Processing: 0x0 0x5 0x0 0x0 0x0 0xd 0xa 0x3 0xa 0x0 0x8 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:46:55.265 DEBUG (SyncWorker_6) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[8, 0, 0, 0, 0], status=1) [0m
[36m2025-08-06 11:46:55.265 DEBUG (SyncWorker_6) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:46:55.434 DEBUG (SyncWorker_6) [pymodbus.logging] Processing: 0x0 0x6 0x0 0x0 0x0 0x9 0xa 0x3 0x6 0x0 0x5 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:46:55.434 DEBUG (SyncWorker_6) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[5, 0, 0], status=1) [0m
[36m2025-08-06 11:46:55.434 DEBUG (SyncWorker_6) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:46:55.617 DEBUG (SyncWorker_6) [pymodbus.logging] Processing: 0x0 0x7 0x0 0x0 0x0 0xd 0xa 0x3 0xa 0x0 0x8 0x0 0x2 0x0 0x5 0x0 0x5 0x0 0x64[0m
[36m2025-08-06 11:46:55.617 DEBUG (SyncWorker_6) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[8, 2, 5, 5, 100], status=1) [0m
[36m2025-08-06 11:46:55.617 DEBUG (SyncWorker_6) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:46:55.797 DEBUG (SyncWorker_6) [pymodbus.logging] Processing: 0x0 0x8 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:46:55.797 DEBUG (SyncWorker_6) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 0, 0], status=1) [0m
[36m2025-08-06 11:46:55.797 DEBUG (SyncWorker_6) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:46:55.979 DEBUG (SyncWorker_6) [pymodbus.logging] Processing: 0x0 0x9 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x1 0x0 0x0 0x0 0x1e 0x0 0x50[0m
[36m2025-08-06 11:46:55.980 DEBUG (SyncWorker_6) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[1, 0, 30, 80], status=1) [0m
[36m2025-08-06 11:46:55.980 DEBUG (SyncWorker_6) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:46:55.981 DEBUG (MainThread) [custom_components.thessla_green_modbus.coordinator] Data update completed in 11.58s (avg: 11.64s, success rate: 100.0%)[0m
[36m2025-08-06 11:46:55.981 DEBUG (MainThread) [custom_components.thessla_green_modbus.coordinator] Finished fetching thessla_green_modbus data in 11.576 seconds (success: True)[0m
[33m2025-08-06 11:46:59.936 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:47:00.712 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[36m2025-08-06 11:47:26.412 DEBUG (SyncWorker_1) [pymodbus.logging] Connection to Modbus server established. Socket ('192.168.1.83', 55582)[0m
[33m2025-08-06 11:47:35.009 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[33m2025-08-06 11:47:35.010 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities number.rekuperator_predkosc are missing or not currently available[0m
[36m2025-08-06 11:47:36.489 DEBUG (SyncWorker_1) [pymodbus.logging] Processing: 0x0 0x1 0x0 0x0 0x0 0x11 0xa 0x4 0xe 0x0 0xbf 0x0 0xc7 0x0 0xfb 0x0 0xc4 0x80 0x0 0x80 0x0 0x1 0xd[0m
[36m2025-08-06 11:47:36.489 DEBUG (SyncWorker_1) [pymodbus.logging] decoded PDU function_code(4 sub -1) -> ReadInputRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[191, 199, 251, 196, 32768, 32768, 269], status=1) [0m
[36m2025-08-06 11:47:36.489 DEBUG (SyncWorker_1) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:47:36.675 DEBUG (SyncWorker_1) [pymodbus.logging] Processing: 0x0 0x2 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x0 0x0 0x0 0x0 0x1 0x0 0x0[0m
[36m2025-08-06 11:47:36.676 DEBUG (SyncWorker_1) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 1, 0], status=1) [0m
[36m2025-08-06 11:47:36.676 DEBUG (SyncWorker_1) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:47:36.845 DEBUG (SyncWorker_1) [pymodbus.logging] Processing: 0x0 0x3 0x0 0x0 0x0 0x9 0xa 0x3 0x6 0xd 0xcd 0xe 0xd 0x8 0x0[0m
[36m2025-08-06 11:47:36.845 DEBUG (SyncWorker_1) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[3533, 3597, 2048], status=1) [0m
[36m2025-08-06 11:47:36.845 DEBUG (SyncWorker_1) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:47:37.028 DEBUG (SyncWorker_1) [pymodbus.logging] Processing: 0x0 0x4 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:47:37.029 DEBUG (SyncWorker_1) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 0, 0], status=1) [0m
[36m2025-08-06 11:47:37.029 DEBUG (SyncWorker_1) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:47:37.212 DEBUG (SyncWorker_1) [pymodbus.logging] Processing: 0x0 0x5 0x0 0x0 0x0 0xd 0xa 0x3 0xa 0x0 0x8 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:47:37.212 DEBUG (SyncWorker_1) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[8, 0, 0, 0, 0], status=1) [0m
[36m2025-08-06 11:47:37.212 DEBUG (SyncWorker_1) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:47:37.390 DEBUG (SyncWorker_1) [pymodbus.logging] Processing: 0x0 0x6 0x0 0x0 0x0 0x9 0xa 0x3 0x6 0x0 0x5 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:47:37.390 DEBUG (SyncWorker_1) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[5, 0, 0], status=1) [0m
[36m2025-08-06 11:47:37.391 DEBUG (SyncWorker_1) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:47:37.593 DEBUG (SyncWorker_1) [pymodbus.logging] Processing: 0x0 0x7 0x0 0x0 0x0 0xd 0xa 0x3 0xa 0x0 0x8 0x0 0x2 0x0 0x5 0x0 0x5 0x0 0x64[0m
[36m2025-08-06 11:47:37.594 DEBUG (SyncWorker_1) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[8, 2, 5, 5, 100], status=1) [0m
[36m2025-08-06 11:47:37.594 DEBUG (SyncWorker_1) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:47:37.783 DEBUG (SyncWorker_1) [pymodbus.logging] Processing: 0x0 0x8 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0[0m
[36m2025-08-06 11:47:37.784 DEBUG (SyncWorker_1) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[0, 0, 0, 0], status=1) [0m
[36m2025-08-06 11:47:37.784 DEBUG (SyncWorker_1) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:47:37.956 DEBUG (SyncWorker_1) [pymodbus.logging] Processing: 0x0 0x9 0x0 0x0 0x0 0xb 0xa 0x3 0x8 0x0 0x1 0x0 0x0 0x0 0x1e 0x0 0x50[0m
[36m2025-08-06 11:47:37.957 DEBUG (SyncWorker_1) [pymodbus.logging] decoded PDU function_code(3 sub -1) -> ReadHoldingRegistersResponse(dev_id=0, transaction_id=0, address=0, count=0, bits=[], registers=[1, 0, 30, 80], status=1) [0m
[36m2025-08-06 11:47:37.957 DEBUG (SyncWorker_1) [pymodbus.logging] Frame advanced, resetting header!![0m
[36m2025-08-06 11:47:37.958 DEBUG (MainThread) [custom_components.thessla_green_modbus.coordinator] Data update completed in 11.55s (avg: 11.63s, success rate: 100.0%)[0m
[36m2025-08-06 11:47:37.958 DEBUG (MainThread) [custom_components.thessla_green_modbus.coordinator] Finished fetching thessla_green_modbus data in 11.553 seconds (success: True)[0m
[33m2025-08-06 11:47:59.988 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:307]: dallas_temp.sensor cleared Warning flag[0m
[33m2025-08-06 11:48:00.767 WARNING (MainThread) [homeassistant.components.esphome.manager] Sensory: [W][component:279]: dallas_temp.sensor set Warning flag: scratch pad checksum invalid[0m
[36m2025-08-06 11:48:08.414 DEBUG (SyncWorker_0) [pymodbus.logging] Connection to Modbus server established. Socket ('192.168.1.83', 46134)[0m
